spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testcrud_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: dldbgus71!
    driver-class-name: com.mysql.cj.jdbc.Driver